# Generated by Django 5.0.6 on 2024-06-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MicroVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('api_socket', models.CharField(max_length=200)),
                ('tap_dev', models.CharField(max_length=200)),
                ('tap_ip', models.CharField(max_length=200)),
                ('tap_netmask', models.CharField(max_length=200)),
                ('host_iface', models.CharField(max_length=200)),
                ('karnel', models.CharField(max_length=200)),
                ('fc_mac', models.CharField(max_length=200)),
            ],
        ),
    ]
