# Generated by Django 5.0.6 on 2024-06-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microvm',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='microvm',
            name='karnel',
        ),
        migrations.RemoveField(
            model_name='microvm',
            name='tap_netmask',
        ),
        migrations.AddField(
            model_name='microvm',
            name='eth_ip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='microvm',
            name='kernel',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='microvm',
            name='ubuntu_iso',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microvm',
            name='api_socket',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microvm',
            name='fc_mac',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microvm',
            name='host_iface',
            field=models.CharField(default='eth0', editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microvm',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microvm',
            name='tap_dev',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='microvm',
            name='tap_ip',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
