# Generated by Django 5.0.6 on 2024-06-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0003_alter_microvm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='microvm',
            name='log_file',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
