# Generated by Django 5.0.6 on 2024-06-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0004_microvm_log_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpTableRouter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server_ip', models.CharField(editable=False, max_length=200)),
                ('micro_vm_ip', models.CharField(editable=False, max_length=200)),
            ],
        ),
    ]
