# Generated by Django 5.0.6 on 2024-06-23 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0005_iptablerouter'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptablerouter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablerouter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
